---
- name: Create VM and mount ISO in vCenter
  hosts: localhost

  tasks:
    - name: Create VM (with ISO mounted to CD-ROM)
      vmware.vmware_rest.vcenter_vm:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: "{{ validate_certs }}"

        placement:
          datastore: "{{ datastore_name }}"
          folder: "{{ vm_folder_relative_path }}"
   
        name: "{{ vm_name }}"
        guest_OS: "{{ guest_os }}"
        hardware_version: "{{ hardware_version }}"
        memory:
          size_MiB: "{{ mem_mib }}"

        cpu:
          count: "{{ cpu_count }}"

        disks:
          - type: SATA
            new_vmdk:
              name: "{{ vm_name }}-disk0"
              # capacity in bytes per module doc; use GiB -> bytes
              capacity: "{{ disk0_gb | int * 1024 * 1024 * 1024 }}"

        nics:
          - backing:
              type: "STANDARD_PORTGROUP"
              network: "{{ network_id }}"
            type: "VMXNET3"
            start_connected: true

        cdroms:
          - type: "SATA"
            start_connected: true
            backing:
              type: "ISO_FILE"
              iso_file: "{{ iso_datastore_path }}"
      register: new_vm
