---
- name: Create a VM
  hosts: localhost
  gather_facts: false

  vars:
    vcenter_hostname: "192.168.85.60"
    vcenter_username: "Administrator@vsphere.local"
    vcenter_password: "Nable@123"
    validate_certs: false

    datacenter: "DC01"
    folder: "/DC01/vm/Provision"              # adjust if you have subfolders
    #cluster: "Cluster01"            # or use resource_pool instead
    datastore: "datastore02"

    vm_name: "new-vm-001"
    guest_id: "rhel9_64Guest"       # examples: ubuntu64Guest, windows9Server64Guest, rhel8_64Guest
    cpu: 2
    memory_mb: 4096

    disk_gb: 60
    network_name: "85-Network"

    power_state: "poweredoff"       # keep off = "create only"

  tasks:
    - name: Create VM (no template)
      vmware.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"

        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        #cluster: "{{ cluster }}"
        datastore: "{{ datastore }}"

        name: "{{ vm_name }}"
        guest_id: "{{ guest_id }}"
        state: "{{ power_state }}"

        hardware:
          num_cpus: "{{ cpu }}"
          memory_mb: "{{ memory_mb }}"

        disk:
          - size_gb: "{{ disk_gb }}"
            type: thin
            datastore: "{{ datastore }}"

        networks:
          - name: "{{ network_name }}"
            type: dhcp

        wait_for_ip_address: false
      delegate_to: localhost
