---
- name: Create VM (no template) in BI datacenter on a standalone ESXi host
  hosts: localhost
  gather_facts: false

  vars:
    # vCenter access
    vcenter_hostname: "192.168.85.60"
    vcenter_username: "Administrator@vsphere.local"
    vcenter_password: "Nable@123"
    vcenter_validate_certs: false

    # vSphere inventory (from your screenshot)
    datacenter_name: "BI"
    esxi_host: "192.168.50.58"     # change to 192.168.50.58 or 192.168.50.59 if needed

    # Placement targets (you must set these two)
    datastore_name: "datastore2"
    network_name: "85-Network"

    # VM spec
    vm_name: "new-vm-001"
    guest_os: "RHEL_9_64"          # example; adjust to your OS enum
    cpu_count: 2
    memory_mib: 4096
    disk0_gb: 40

    # Standard paths used by vmware_rest lookup plugins
    vm_folder_path: "/{{ datacenter_name }}/vm"
    host_path: "/{{ datacenter_name }}/host/{{ esxi_host }}"
    rp_path: "/{{ datacenter_name }}/host/{{ esxi_host }}/Resources"
    ds_path: "/{{ datacenter_name }}/datastore/{{ datastore_name }}"
    net_path: "/{{ datacenter_name }}/network/{{ network_name }}"

    environment:
    VMWARE_HOST: "{{ vcenter_hostname }}"
    VMWARE_USER: "{{ vcenter_username }}"
    VMWARE_PASSWORD: "{{ vcenter_password }}"
    VMWARE_VALIDATE_CERTS: "{{ vcenter_validate_certs | ternary('true','false') }}"

  tasks:
    - name: Create VM (powered off) on standalone ESXi host
      vmware.vmware_rest.vcenter_vm:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: "{{ vcenter_validate_certs }}"
        state: present

        name: "{{ vm_name }}"
        guest_OS: "{{ guest_os }}"   # required field for create :contentReference[oaicite:2]{index=2}

        placement:
          folder: "{{ lookup('vmware.vmware_rest.folder_moid', vm_folder_path) }}"
          datastore: "{{ lookup('vmware.vmware_rest.datastore_moid', ds_path) }}"
          host: "{{ lookup('vmware.vmware_rest.host_moid', host_path) }}"
          resource_pool: "{{ lookup('vmware.vmware_rest.resource_pool_moid', rp_path) }}"
          # placement.host is supported :contentReference[oaicite:3]{index=3}

        cpu:
          count: "{{ cpu_count }}"
        memory:
          size_MiB: "{{ memory_mib }}"

        disks:
          - type: SATA
            new_vmdk:
              name: "{{ vm_name }}-disk0"
              capacity: "{{ (disk0_gb | int) * 1024 * 1024 * 1024 }}"  # bytes

        nics:
          - type: VMXNET3
            backing:
              type: STANDARD_PORTGROUP
              network: "{{ lookup('vmware.vmware_rest.network_moid', net_path) }}"
      register: vm_result

    - name: Show created VM MOID
      ansible.builtin.debug:
        msg: "Created VM id: {{ vm_result.id }}"
