---
- name: Create VM (no template) in BI datacenter on a standalone ESXi host
  hosts: localhost
  gather_facts: false
  collections:
    - vmware.vmware_rest
    - vmware.vmware

  vars:
    vcenter_hostname: "192.168.85.60"
    vcenter_username: "Administrator@vsphere.local"
    vcenter_password: "Nable@123"     # <-- use AAP credential in real usage
    vcenter_validate_certs: false

    datacenter_name: "BI"
    esxi_host: "192.168.50.58"

    datastore_name: "datastore2"
    network_name: "85-Network"

    vm_name: "new-vm-001"
    guest_os: "RHEL_9_64"
    cpu_count: 2
    memory_mib: 4096
    disk0_gb: 40

    # Inventory paths (as shown in vCenter UI)
    folder_path: "/{{ datacenter_name }}/vm"
    host_path: "/{{ datacenter_name }}/host/{{ esxi_host }}"
    #rp_path: "/{{ datacenter_name }}/host/{{ esxi_host }}/Resources"
    ds_path: "/{{ datacenter_name }}/datastore/{{ datastore_name }}"
    net_path: "/{{ datacenter_name }}/network/{{ network_name }}"

  # ✅ Correct env var names that the lookup plugin reads
  environment:
    VMWARE_HOST: "{{ vcenter_hostname }}"
    VMWARE_USER: "{{ vcenter_username }}"
    VMWARE_PASSWORD: "{{ vcenter_password }}"
    VMWARE_VALIDATE_CERTS: "{{ 'false' if (not vcenter_validate_certs) else 'true' }}"

  tasks:
    - name: Resolve MoIDs using inventory paths
      ansible.builtin.set_fact:
        folder_moid: "{{ lookup('vmware.vmware.moid_from_path', folder_path, type='folder') }}"
        host_moid: "{{ lookup('vmware.vmware.moid_from_path', host_path, type='host') }}"
        #rp_moid: "{{ lookup('vmware.vmware.moid_from_path', rp_path, type='resource_pool') }}"
        ds_moid: "{{ lookup('vmware.vmware.moid_from_path', ds_path, type='datastore') }}"
        net_moid: "{{ lookup('vmware.vmware.moid_from_path', net_path, type='network') }}"

    - name: Create VM (powered off)
      vmware.vmware_rest.vcenter_vm:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: "{{ vcenter_validate_certs }}"
        state: present

        name: "{{ vm_name }}"
        guest_OS: "{{ guest_os }}"

        placement:
          folder: "{{ folder_moid }}"
          host: "{{ host_moid }}"
          #resource_pool: "{{ rp_moid }}"
          datastore: "{{ ds_moid }}"

        cpu:
          count: "{{ cpu_count }}"
        memory:
          size_MiB: "{{ memory_mib }}"

        disks:
          - type: SATA
            new_vmdk:
              name: "{{ vm_name }}-disk0"
              capacity: "{{ (disk0_gb | int) * 1024 * 1024 * 1024 }}"

        nics:
          - type: VMXNET3
            start_connected: true
            backing:
              type: STANDARD_PORTGROUP
              network: "{{ net_moid }}"
      register: vm_result

    - name: Show created VM id
      ansible.builtin.debug:
        msg: "Created VM id: {{ vm_result.id }}"
