---
- name: Create vCenter VM folder
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Create VM folder path
      vmware.vmware.folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter }}"
        folder_type: "vm"
        relative_path: "{{ vm_folder_relative_path }}"
        state: present
