- name: Create a VM
  hosts: localhost
  vmware.vmware_rest.vcenter_vm:
    placement:
      datastore: "{{ lookup('vmware.vmware_rest.datastore_moid', '/BI/datastore/datastore2') }}"
      folder: "{{ lookup('vmware.vmware_rest.folder_moid', '/BI/vm/Provition') }}"
    name: test_vm1
    guest_OS: RHEL_8_64
    hardware_version: VMX_11
    memory:
      hot_add_enabled: true
      size_MiB: 1024
  register: my_vm
